version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor:
      name: node/default
      tag: '24.4'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint, build & export
          command: npm run export:with-typedoc
workflows:
  build:
    jobs:
      - build
